apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tfsa-transaction-agent.name" . }}
  labels:
    {{- include "tfsa-transaction-agent.labels" . | nindent 4 }}
  annotations:
    {{- include "tfsa-transaction-agent.argocd-syncwave" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-
    # LLm
    quarkus.langchain4j.openai.chat-model.model-name={{ .Values.llm.tfsaTransaction.modelName }}
    quarkus.langchain4j.openai.api-key={{ .Values.llm.tfsaTransaction.apiKey }}
    quarkus.langchain4j.openai.base-url={{ .Values.llm.tfsaTransaction.baseUrl }}

    quarkus.langchain4j.openai.tfsatransaction.chat-model.model-name={{ .Values.llm.tfsaTransaction.modelName }}
    quarkus.langchain4j.openai.tfsatransaction.api-key={{ .Values.llm.tfsaTransaction.apiKey }}
    quarkus.langchain4j.openai.tfsatransaction.base-url={{ .Values.llm.tfsaTransaction.baseUrl }}
    quarkus.langchain4j.openai.tfsatransaction.log-requests={{ .Values.llm.tfsaTransaction.logRequests }}
    quarkus.langchain4j.openai.tfsatransaction.log-responses={{ .Values.llm.tfsaTransaction.logResponses }}
    quarkus.langchain4j.openai.tfsatransaction.chat-model.temperature={{ .Values.llm.tfsaTransaction.temperature }}
    quarkus.langchain4j.openai.tfsatransaction.timeout={{ .Values.llm.tfsaTransaction.timeout }}
    quarkus.langchain4j.openai.tfsatransaction.chat-model.strict-json-schema={{ .Values.llm.tfsaTransaction.strictJsonSchema }}
    quarkus.langchain4j.openai.tfsatransaction.chat-model.response-format={{ .Values.llm.tfsaTransaction.responseFormat }}

    agent.url=https://{{ .Values.route.host }}.{{ .Values.subdomain }}
