{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tfsa-transaction-agent.serviceAccountName" . }}
  labels:
    {{- include "tfsa-transaction-agent.labels" . | nindent 4 }}
  annotations:
    {{- include "tfsa-transaction-agent.argocd-syncwave" . | nindent 4 }}
{{- end }}
