apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tfsa-calculation-agent.name" . }}
  labels:
    {{- include "tfsa-calculation-agent.labels" . | nindent 4 }}
  annotations:
    {{- include "tfsa-calculation-agent.argocd-syncwave" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-
    # LLm
    quarkus.langchain4j.openai.chat-model.model-name={{ .Values.llm.tfsaCalculation.modelName }}
    quarkus.langchain4j.openai.api-key={{ .Values.llm.tfsaCalculation.apiKey }}
    quarkus.langchain4j.openai.base-url={{ .Values.llm.tfsaCalculation.baseUrl }}

    quarkus.langchain4j.openai.tfsacalculation.chat-model.model-name={{ .Values.llm.tfsaCalculation.modelName }}
    quarkus.langchain4j.openai.tfsacalculation.api-key={{ .Values.llm.tfsaCalculation.apiKey }}
    quarkus.langchain4j.openai.tfsacalculation.base-url={{ .Values.llm.tfsaCalculation.baseUrl }}
    quarkus.langchain4j.openai.tfsacalculation.log-requests={{ .Values.llm.tfsaCalculation.logRequests }}
    quarkus.langchain4j.openai.tfsacalculation.log-responses={{ .Values.llm.tfsaCalculation.logResponses }}
    quarkus.langchain4j.openai.tfsacalculation.chat-model.temperature={{ .Values.llm.tfsaCalculation.temperature }}
    quarkus.langchain4j.openai.tfsacalculation.timeout={{ .Values.llm.tfsaCalculation.timeout }}
    quarkus.langchain4j.openai.tfsacalculation.chat-model.strict-json-schema={{ .Values.llm.tfsaCalculation.strictJsonSchema }}
    quarkus.langchain4j.openai.tfsacalculation.chat-model.response-format={{ .Values.llm.tfsaCalculation.responseFormat }}

    agent.url=https://{{ .Values.route.host }}.{{ .Values.subdomain }}
